import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EmpireOne Health | Healthcare BPO & RCM Services",
  description: "Generated by create next app",
  icons: {
<<<<<<< HEAD
    icon: "/images/EmpireOne CX logo.webp",
=======
    icon: "/images/eo-logo.webp",
>>>>>>> 257cc616607f813026a1c2d8451e9dcaa91939d6
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
